/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicRegionsRouteImport } from './routes/api/public/regions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegionsRoute = ApiPublicRegionsRouteImport.update({
  id: '/api/public/regions',
  path: '/api/public/regions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/regions': typeof ApiPublicRegionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/regions': typeof ApiPublicRegionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/regions': typeof ApiPublicRegionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analysis/$id' | '/api/public/health' | '/api/public/regions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis/$id' | '/api/public/health' | '/api/public/regions'
  id:
    | '__root__'
    | '/'
    | '/analysis/$id'
    | '/api/public/health'
    | '/api/public/regions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRegionsRoute: typeof ApiPublicRegionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/regions': {
      id: '/api/public/regions'
      path: '/api/public/regions'
      fullPath: '/api/public/regions'
      preLoaderRoute: typeof ApiPublicRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRegionsRoute: ApiPublicRegionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
